title: Hosted Marginalia
author: Akshit Kumar
email: akshitdotkr@gmail.com
tagline: scribbles on the margins, now hosted
url: https://komikat.github.io
permalink: pretty
env: development
future: true
description: akshit's blog
baseurl: "" # /blog
paginate: 10

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  
sass:
  sass_dir: _sass


github_username: komikat
twitter_username: akshitkr
instagram_username: akshitkr_
